image: proboci/ubuntu:20.04-php8.0

steps:
  - name: Set Up Pre-requisites Database
    plugin: Drupal
    databaseName: drupal2
    databaseUser: sysop-user
    docroot: docroot/web
    settingsAppend: |
      $settings['trusted_host_patterns'] = ['.*'];
      $settings['file_private_path'] = '/src/private';
      $config['search_api.server.solr']['backend_config']['connector'] = 'standard';
      $config['search_api.server.solr']['backend_config']['connector_config']['scheme'] = 'http';
      $config['search_api.server.solr']['backend_config']['connector_config']['host'] = 'localhost';
      $config['search_api.server.solr']['backend_config']['connector_config']['core'] = 'drupal8';
      $config['search_api.server.solr']['backend_config']['connector_config']['path'] = '/';
      $config['search_api.server.solr']['backend_config']['connector_config']['timeout'] = '5';
      $config['search_api.server.solr']['backend_config']['connector_config']['index_timeout'] = '5';
      $config['search_api.server.solr']['backend_config']['connector_config']['optimize_timeout'] = '10';
      $config['search_api.server.solr']['backend_config']['connector_config']['finalize_timeout'] = '30';
      $config['search_api.server.solr']['backend_config']['connector_config']['commit_within'] = '1000';
  
  - name: Build Drupal 9
    plugin: Script
    script: |
      rm -rf /var/www/html
      cd $SRC_DIR
      export PATH="/src/docroot/vendor/drush/drush:$PATH"
      composer create-project drupal/recommended-project docroot
      cd /src/docroot
      composer require drush/drush drupal/admin_toolbar drupal/search_api drupal/search_api_solr mbagnall/gov-info
      cd /src/docroot/web
      drush site:install -y --db-url=mysql://root:strongpassword@localhost/drupal --account-pass=password 
      cd /src/docroot/web/modules
      wget https://github.com/ElusiveMind/govinfo/archive/main.zip
      unzip main.zip
      drush pm:enable -y govinfo
      drush pm:enable -y admin_toolbar
      cd /var/www
      ln -s /src/docroot/web html
      ln -s /src/docroot/vendor/drush/drush/drush /usr/local/bin/drush
      chmod -R 777 /src/docroot/web/sites/default/files
      drush cr

