image: mbagnall/ubuntu:18.04-php8.0
assets:
  - drupal.sql.gz
steps:
  - name: Set Up Pre-requisites Database
    plugin: Drupal
    database: drupal.sql.gz
    drupalVersion: 9
    databaseName: drupal2
    databaseUser: sysop-user
    docroot: docroot/web

  - name: Build Drupal 9
    plugin: Script
    script: |
      rm -rf /var/www/html
      cd $SRC_DIR
      export PATH="/src/docroot/vendor/drush/drush:$PATH"
      composer create-project drupal/recommended-project docroot
      cd /src/docroot
      composer require drush/drush drupal/admin_toolbar drupal/search_api drupal/search_api_solr mbagnall/gov-info
      cd /src/docroot/web/modules
      wget https://github.com/ElusiveMind/govinfo/archive/main.zip
      unzip main.zip
      cd /var/www
      ln -s /src/docroot/web html
      ln -s /src/docroot/vendor/drush/drush/drush /usr/local/bin/drush
      chmod -R 777 /src/docroot/web/sites/default
      drush cr

