image: mbagnall/ubuntu:18.04-php8.0

steps:
  - name: Set Up Pre-requisites Database
    plugin: LAMPApp
    databaseName: drupal2
    databaseUser: sysop-user
    docroot: docroot/web

  - name: Build Drupal 9
    plugin: Script
    script: |
      cd $SRC_DIR
      export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"
      composer create-project drupal/recommended-project docroot
      cd /src/docroot
      composer require drush/drush
      cd /src/docroot/web
      drush site:install -y --db-url=mysql://root:strongpassword@localhost/drupal --account-pass=password 
      cd /src/docroot/web/modules
      wget https://github.com/ElusiveMind/govinfo/archive/main.zip
      unzip main.zip
      drush pm:enable -y govinfo
      cd /var/www
      ln -s /src/docroot/web html

