image: mbagnall/ubuntu:18.04-php8.0

steps:
  - name: Set Up Pre-requisites Database
    plugin: LAMPApp
    databaseName: drupal2
    databaseUser: sysop-user
    docroot: docroot/web

  - name: Build Drupal 9
    plugin: Script
    script: |
      cd $SRC_DIR
      export PATH="/src/docroot/vendor/drush/drush:$PATH"
      composer create-project drupal/recommended-project docroot
      cd /src/docroot
      composer require drush/drush drupal/admin_toolbar
      cd /src/docroot/web
      drush site:install -y --db-url=mysql://root:strongpassword@localhost/drupal --account-pass=password 
      cd /src/docroot/web/modules
      wget https://github.com/ElusiveMind/govinfo/archive/main.zip
      unzip main.zip
      drush pm:enable -y govinfo
      drush pm:enable -y admin_toolbar
      cd /var/www
      ln -s /src/docroot/web html
      chmod -R 777 /src/docroot/wen/sites/default
      drush cr

